#ifndef UAV_PARAM_KEYS_H
#define UAV_PARAM_KEYS_H
/* Stable IDs. Extend with a new schema, never reuse a retired key. */
enum { UAV_PARAM_IMU_LEGACY=1, UAV_PARAM_REMOTE=2, UAV_PARAM_PID=3,
       UAV_PARAM_MAG=4, UAV_PARAM_ACCEL=5, UAV_PARAM_GYRO_THERMAL=6,
       UAV_PARAM_IMU_FILTERS=7, UAV_PARAM_SENSOR_MOUNT=8, UAV_PARAM_SAFETY=9,
       UAV_PARAM_BARO=10, UAV_PARAM_FLOW=11, UAV_PARAM_BATTERY=12,
       UAV_PARAM_TELEMETRY=13, UAV_PARAM_DISPLAY=14,
       UAV_PARAM_RESERVED15=15, UAV_PARAM_RESERVED16=16 };
#define UAV_PARAM_MAG_BYTES 64u
#define UAV_PARAM_ACCEL_BYTES 40u
#endif
